#!/bin/sh
set -e

# Pre-removal script for postgresql-hll

case "$1" in
    remove|upgrade|deconfigure)
        # Nothing special needed
        # Users should DROP EXTENSION hll before removing the package
        echo "Removing postgresql-hll extension files..."
        ;;

    failed-upgrade)
        ;;

    *)
        echo "prerm called with unknown argument \`$1'" >&2
        exit 1
        ;;
esac

exit 0